### ISSUE TITLE
tocs won't export

### ISSUE THREAD

**Issue by Gotomary** [BCcampus/pressbooks-mpdf#50]
mPDF won’t export my table of contents when creating a PDF.

Will you be able to help point me in the right direction as to how to rectify this?

I have tried looking this up on the internet, but there has been no solution.

I’m using Pressbooks Version 4.5.1 and Pressbooks mPDF Version 3.0.0. and Wordpress Version 4.9.4.

I have ticked Display table of contents in the mPDF options tab in Theme Options.

The chapters have names and the parts are not hidden.

Thank you in advance.

 

### System Information

- mPDF for Pressbooks: 3.0 
- Pressbooks: 4.5.1
- WordPress: 4.9.4

**Comment by bdolor** [comment]
thanks @Gotomary for reporting - will try and recreate and get back to you.

**Comment by bdolor** [comment]
@Gotomary 
- if you'd like a quick fix through the GUI, go into _**PDF**_ options and also check 'Display table of contents'. 
- A quick fix via code is to uncomment line https://github.com/BCcampus/pressbooks-mpdf/blob/dev/inc/modules/export/mpdf/class-pdf.php#L601 
- if you're moving to PB5 then this should be resolved with https://github.com/BCcampus/pressbooks-mpdf/commit/c3e4dc7aba7e7f20b2f6baa63f8f3a60208df81d please try https://github.com/BCcampus/pressbooks-mpdf/releases/tag/3.1.0-rc.1

**Comment by Gotomary** [comment]
Hello,

Thank you for your reply.

I have ticked the PDF options Display table of contents, and the file class-pdf.php is uncommented on the line that was suggested. However, the TOC is still not exporting, 

I have written in http://discourse.pressbooks.org and they suggested it could be a bug?

The XHTML file is http://book.phang.org/wp/march/open/download?type=xhtml
and the PDF is http://book.phang.org/wp/march/open/download?type=mpdf

![screenshot](https://user-images.githubusercontent.com/26889132/36622848-f807a590-1953-11e8-84a4-4277c19c2a1e.jpg)

Thanks again for your help.

**Comment by bdolor** [comment]
sorry, could you try commenting out line 600?

**Comment by Gotomary** [comment]
Sorry, wasn't too sure what uncommenting meant (I'm a newbie) so thank you for that. It works!

Have a lovely day. :)
